### ISSUE TITLE
Tracking Editor features 🧨 

### ISSUE THREAD

**Issue by Sagarpreet** [publiclab/PublicLab.Editor#627]
### Resolve outstanding issues remaining from the Summer 2020 Editor Team of 4 work, also documented here: https://pad.publiclab.org/p/editor-tasks 

- [x]  poorly wrapping Markdown button on narrower screens on /post
- STATUS: `Dev completed`
- PR: https://github.com/publiclab/PublicLab.Editor/pull/635

- [x] odd folding (maybe bootstrap 3/4 issue?) of main image column, related to https://github.com/publiclab/PublicLab.Editor/pull/612
- STATUS: `Dev completed`
-  The image issue is resolved here: https://github.com/publiclab/PublicLab.Editor/pull/612, remaining issues solved here: https://github.com/publiclab/plots2/pull/8474, https://github.com/publiclab/PublicLab.Editor/pull/629

- [x] more explanation (help buttons/links) and bootstrap 4 styling of Custom Insert module, possibly covered by https://github.com/publiclab/PublicLab.Editor/pull/566, https://github.com/publiclab/PublicLab.Editor/issues/444
- STATUS: `Dev completed`
- PR: https://github.com/publiclab/PublicLab.Editor/pull/636

- [x] Comment-related issues listed on https://github.com/publiclab/PublicLab.Editor/issues/490#issuecomment-668580733
- STATUS: `Dev completed`
- Issue: https://github.com/publiclab/plots2/issues/8475
- PR: https://github.com/publiclab/plots2/pull/8477

### Editor repo tasks:

- [x]  ensure the formatting toolbar (in both rich and markdown modes) doesn't stick to the bottom of the frame as we scroll far enough down or up that the text area is no longer shown at all
- STATUS: `Done`
- PR: https://github.com/publiclab/PublicLab.Editor/pull/522

### plots2 tasks:

- [x] Re-order legacy and comment toolbars so order of tools matches that of Rich Text Editor, for consistency
- STATUS: `Done`
- Issue: https://github.com/publiclab/plots2/issues/8259
- PR: https://github.com/publiclab/plots2/pull/8252

- [x] Add a button for uploading images to the Wiki Editor toolbar  that would look similar to the Rich Editor's button 
- STATUS: `Done`
-  PR: https://github.com/publiclab/plots2/pull/8252), the image button already exists in comment editor.

- [x]  Repair "click to select an image" functionality on comment (and comment reply) image uploads. 
Issue:
- STATUS: `Done`
- PR: https://github.com/publiclab/plots2/pull/8240/files

- [x] Ensure formatting toolbars on comments appear in all variations:
* comment
* reply to comment
* comment just posted (form inserted via AJAX)
* reply to comment just posted
* editing existing comments
* editing comments just posted
* editing comment replies
* editing comment replies just posted
- STATUS: `Done`
Issue: https://github.com/publiclab/plots2/issues/8475
- PR: https://github.com/publiclab/plots2/pull/8636

- [x] add tags input (matching legacy editor of note editor) to new wiki form and wiki editing page:
 `<input autocomplete="off" class="form-control" id="taginput" tabindex="3" name="tags" type="text" placeholder="balloon-mapping,gulf-coast" data-provide="typeahead">`
* and a controller code addition matching: https://github.com/publiclab/plots2/blob/cd9bd3a2988569632f09c4dd0fad89aa30abbe20/app/controllers/notes_controller.rb#L184-L188 or https://github.com/publiclab/plots2/blob/cd9bd3a2988569632f09c4dd0fad89aa30abbe20/app/controllers/notes_controller.rb#L100-L102
- STATUS: `Done`
- Issue: https://github.com/publiclab/plots2/issues/8229
- PR's: https://github.com/publiclab/plots2/pull/8295/files, https://github.com/publiclab/plots2/pull/8260/files

- [x] adjust OpenGraph tags for questions/notes/wikis so that if no main image is available, openGraph lead image tags show a "scraped" lead image (see how we do this in card display, for example https://publiclab.org/tag/bucket-monitor shows a scraped lead image for https://publiclab.org/notes/kgradow1/07-03-2020/bucket-monitor-prototype)
- STATUS: `Done`
- PR: https://github.com/publiclab/plots2/pull/8291

- [x]  Create a POST route at /editor/preview which simply renders a simulated "note" or "wiki page" using the Markdown in the "body" and "title" POST variables. Nothing is saved in the db, and we repoint all editor Preview buttons at this. (not sure about comment previews though, probably not those). We also make a Preview button for the rich editor pointed at this. All open in a new tab, and should use the [->] "open in new tab" icon from FontAwesome
- STATUS: `Dev Completed`
- Issue: https://github.com/publiclab/plots2/issues/8560
PR: https://github.com/publiclab/plots2/pull/8620, https://github.com/publiclab/plots2/pull/8604

- [x] Add "Preview" button next to the Publish button [ON WHICH EDITORS?] that opens a preview of your content in a new tab
- STATUS: `Dev Completed`
- Issue: https://github.com/publiclab/plots2/issues/8560
PR: https://github.com/publiclab/plots2/pull/8620, https://github.com/publiclab/plots2/pull/8604

- [x] Create and document, in coordination with the Lead Code Coordinator, a “first-timers-only first release” program for use in Outreachy and Google Summer of Code programs. The prototype should be in process as soon as the October 2020 Outreachy Contribution Period and ready to use in the December 1 2020 - March 2 2021 Outreachy Internship period. 	
- STATUS: `Draft completed`
- DRAFTED here: https://docs.google.com/document/d/1GVp0fX79fXEqF6C0VN86CHi40SMS4CIfDZm5NT_9Elk/edit?usp=sharing

**Comment by Sagarpreet** [comment]
`Done` => Merged 
`Needs Clarity` => Need help from @jywarren , @ebarry 
`Work in Progress` => Something is left to do in the PR

**Comment by jywarren** [comment]
This is looking awesome, Sagarpreet, thank you!

**Comment by ebarry** [comment]
Thank you @Sagarpreet ! I don't see any more items labelled "needs clarification" -- is that right?

**Comment by Sagarpreet** [comment]
Correct @ebarry 👍 
These were resolved by Jeff and some by you on gitter 😄

**Comment by jywarren** [comment]
I think we're just waiting on https://github.com/publiclab/plots2/pull/8714 - publishign the Editor v3 to plots2 -- plus the Preview route and follow-ups, right?

**Comment by sagarpreet-chadha** [comment]
Correct Jeff 👍

**Comment by Sagarpreet** [comment]
NPM release for all above changes: https://github.com/publiclab/PublicLab.Editor/pull/657
plots2 integration of all above changes: https://github.com/publiclab/plots2/pull/8744

**Comment by jywarren** [comment]
Noting bold bug PR at https://github.com/publiclab/PublicLab.Editor/pull/659 as well! Thank you!!

**Comment by jywarren** [comment]
Updated the Preview project checkboxes!!!! Yay!!!

**Comment by jywarren** [comment]
This is all done, i believe!!! Thanks so much @Sagarpreet !!!!
