### ISSUE TITLE
[Planning] Comment Editor Overhaul Project

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/PublicLab.Editor#630]
## Description

We have a collection of improvements, bugfixes, and refinements to our aging Comment editor subcomponent on the PublicLab.org website. The comment editor is used in various “variants” with shared code, complicating debugging (i.e. fixing the bug in one place can introduce a bug in another). This is a great case for system tests, where we can ensure behaviors are preserved, and for writing these tests before making any major code changes - as well as for identifying bugs by writing tests to demonstrate them, followed by submitting a fix within the same pull request, which gets the test to pass -- Test Driven Development. We have prioritized a list of bugs and refinements we’d like to fix first, and have then outlined a set of changes that could make the code more compact, readable, and maintainable to reduce future workload. 
If an applicant has a lot of React experience, we would consider a React implementation, but are cautious about a refactor and would like to see past React work before considering such a path.We have compiled an “overview” document to compare the different editor features and instances across the Public Lab ecosystem here:  https://docs.google.com/document/d/1hOqa4tC0jqEuSaur1zKMtnxnknkARui3HTKqO3AUFMA/edit

## Task List

- Separate out critical bugs to fix immediately, such as image upload, format and toolbar issues
- [ ] Formatting buttons on comment editor are cross-wired: https://publiclab.org/questions/kgradow1/07-14-2020/documenting-public-lab-projects-on-github. This can happen for various bugs if unique IDs are not well-managed between different comment boxes on the same page
- [ ] Write system tests to safeguard these bugs for future cases
- [ ] Remove Templates button to simplify
- [ ] Ensure Recovery is consistently working
- [ ] Make all comment editor toolbars consistent, across variants: https://docs.google.com/document/d/1hOqa4tC0jqEuSaur1zKMtnxnknkARui3HTKqO3AUFMA/edit
- [ ] Write system tests to confirm basic functionality in each of 8 usage scenarios (comment, comment response, question comment, question comment response, editing all above types, editing/using all above types after having just posted them (i.e. having been inserted using AJAX).  https://github.com/publiclab/plots2/blob/main/test/system/comment_test.rb 
-  Explore comment types on our test server at https://stable.publiclab.org/ here  https://stable.publiclab.org/comments 
- Regular comments: https://stable.publiclab.org/notes/mimiss/01-10-2020/gulf-coast-educators-join-public-lab-this-summer-for-a-classroom-community-science-workshop#c27102 
-  Question comments: https://stable.publiclab.org/questions/kgradow1/06-25-2020/what-causes-shimmering-air-above-flares#c27096  
-  Also consider comments on wiki pages: https://publiclab.org/wiki/coqui/comments 
- [ ] Consolidating comment/question/response types will reduce the # of tests we need to look for
- [ ] Test for multiple types of comment boxes on a single page
- [ ] Consolidate and organize tests so that we run each type of test on each variant of the comment editor

-  Later in project - after checking in with everyone about improved state of editor consider:
- [ ] Reorganizing/consolidating comment editor code and code organization or architecture which would simplify, reduce redundancy, and ease maintenance going forward. Discuss with Jeff whether spinning it out like other libraries makes sense, like: https://github.com/publiclab/inline-markdown-editor

**Comment by jywarren** [comment]
For the later stages of the Comment Editor project when it might be spun out into its own repository, we may want to carefully consider this workflow documented by Sagarpreet for what would help create a standard release cycle!

https://publiclab.org/notes/sagarpreet_chadha/10-20-2020/first-timer-only-release-workflow
