### ISSUE TITLE
[Planning] Standardize Editors + Remaining bugs

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/PublicLab.Editor#648]
## Description

I am helping out with the winter prioritization session so have been reviewing recent work. I made a parsed down summary of what's left over from the Editor Overhaul project. I ended up with a lot of bullets, so decided to remove the specifics from the session discussion because it's overkill and move it here.

This wasn't signed off by anyone so feel free to change the "[Planning]" title - it's just building on the work Emily did on standardizing the toolbars. 

Linking this to #630 because it is ,most likely in some way interdependent with it.

## Task List
These should all be fixed, but BOLD bullets are in my opinion showstoppers.

### PublicLab.Editor: 
- [ ] Numbering is reset if photos are in the list #128
- [ ] Custom insert doesn’t properly insert a wiki as a grid
### Research Note Editor:
- [ ] Toolbar still needs a positioning (UI) fix
- [ ] **Center formatting breaks if you toggle to markdown mode, and can’t fix it by toggling back to rich text #428**
### Wiki Editor:
- [ ] **Save and Recover buttons don’t work properly**
- [ ] Can’t add tags before publishing
- [ ] An error creating a new wiki gets you redirected to a form with the Research Editor interface (and publishing breaks)
 If you publish a wiki with a duplicate title, you will lose all you work and be redirected to the other wikis page
- [ ] **Revert button doesn't work properly**
- [ ] **Can’t delete a wiki that has more than 1 contributor**
- [ ] **If you publish a wiki with a title that already exists, on publish you will be redirected to that existing wiki and lose all you work**

**Comment by sashadev-sky** [comment]
@cesswairimu @ebarry @jywarren @publiclab/comment-maintainers @publiclab/editor

**Comment by sashadev-sky** [comment]
Looking for some input here about availability and thoughts. I think it would be "small wrap-up contract for editor overhaul"?

**Comment by ebarry** [comment]
Hi @sashadev-sky it's great to have a fresh look across all this. Can you also look at the short list that @sagarpreet-chadha is working from this month? https://pad.publiclab.org/p/editor-tasks? Are any of the ones you highlighted NOT in there already? Thank you all!🌳

**Comment by sagarpreet-chadha** [comment]
Hey @sashadev-sky ,
Adding to @ebarry comment above, I have made tracking issue here:
https://github.com/publiclab/PublicLab.Editor/issues/627#issuecomment-704706134
Thanks 😄

**Comment by jywarren** [comment]
Hi all, this is great, thank you!

>  Numbering is reset ...

Noting that we'd suggested a GitHub Markdown style fix but @sashadev-sky also discovered [a workaround](https://github.com/publiclab/PublicLab.Editor/issues/128#issuecomment-715415384)

> Custom insert doesn’t properly insert a wiki as a grid

Let's open a breakout issue for this and see if @keshav234156 has thoughts on it? Perhaps we can start with a test demonstrating the issue. Thanks!

Also what was the specific issue with the toolbar? Noting theres work on this in #600 #599 #496 #522 and others, so may need to clarify what the problem + solution are, since the original issue flipped back and forth a few times due to varying user preferences. Thanks!

**Comment by sashadev-sky** [comment]
@ebarry none of these are on #627
