### ISSUE TITLE
Outreachy proposal planning issue

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#742]
* [ ] install, build, and run tests on the library itself
* [ ] investigate and debug blocked Jasmine test at https://github.com/publiclab/PublicLab.Editor/issues/721 
* [ ] investigate and debug stalled Jasmine tests at https://github.com/publiclab/PublicLab.Editor/issues/741
* [ ] learn about and understand the nested structure of these repositories, with Domador/Megamark included into Woofmark, included into PublicLab.Editor, included into plots2 - and the role of the NPM registry and semantic versioning (https://docs.npmjs.com/about-semantic-versioning) in managing such integrated code
* [ ] prepare and publish a new version of PublicLab.Editor and see it appear in https://github.com/publiclab/plots2/ with the help of Dependabot, and see it publish into production
* [ ] investigate and debug intermittent test failures documented at  https://github.com/publiclab/PublicLab.Editor/issues/683 
* [ ] drop footnote-style linking in woofmark in favor of inline linking https://github.com/jywarren/woofmark/issues/65 
* [ ] debug ES6-related issues in babel compilation of JavaScript: https://github.com/publiclab/PublicLab.Editor/issues/607 
* [ ] reproduce bold/newline errors in a test (as in https://github.com/publiclab/PublicLab.Editor/pull/659) and complete fix begun in https://github.com/publiclab/PublicLab.Editor/issues/658 
* [ ] implement a “pressed” or “active” state for formatting buttons, in CSS: https://github.com/publiclab/PublicLab.Editor/issues/494 
* [ ] modify woofmark library to begin markdown list numbering from the given digit if not “1” in a list of, for example “1. 2. 3.”: https://github.com/publiclab/PublicLab.Editor/issues/128
* [ ] assorted remaining tasks from these lists: https://github.com/publiclab/PublicLab.Editor/issues/490 and https://github.com/publiclab/PublicLab.Editor/issues/648
