### ISSUE TITLE
Plan and checklist for v3.1.0 release

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#814]
Hi @NARUDESIGNS - i think it's time to start preparing a new release, what do you think?

Let's look at the changes since the last release was made; it looks like the change was at https://github.com/publiclab/PublicLab.Editor/commit/0ac18eb0d0b568d8e5813b0ff3f7437454d41298

as part of: https://github.com/publiclab/PublicLab.Editor/pull/712

So, all the changes since then (Apr 13, 2021) can be included into v3.1.0 - what do you say? 

https://github.com/publiclab/PublicLab.Editor/commits/main

The last time we did this in a more organized way was in https://github.com/publiclab/PublicLab.Editor/pull/654, so let's copy the checklist out from there:

## To do:

* [ ] open an issue using the "release" template with this checklist with title `Checklist and coordination for v0.0.0 major/minor/patch release` (see [semantic versioning](https://docs.npmjs.com/about-semantic-versioning/))
* [ ] compile release notes below from corresponding [release milestone](https://github.com/publiclab/PublicLab.Editor/milestones)
* [ ] update version number in `package.json` (ex #1695)
* [ ] finalize and merge to `main` branch (freeze merges to `main` branch until next step)
* [ ] merge, build and publish `/dist/` files to `stable` (merges to `main` branch can resume for next release)
* [ ] create a release on GitHub and use features description + release notes from below
* [ ] tag version number branch (i.e. `v3.0.0`)
* [ ] publish tagged branch to `npm` (actually did from `main` branch -- @jywarren)
* [ ] publish to live `github-pages` demo (with [bash script](https://github.com/publiclab/image-sequencer/pull/1703) from `/scripts/update_demo`) (from within GitPod works well)
* [ ] close this issue!
* [ ] open a matching PR on `plots2` for this new version # (or let Dependabot do it)

How does this sound? When we collect release notes, we can actually use the auto-generator from the "Releases" feature which is new-ish: https://github.com/publiclab/PublicLab.Editor/releases/new

I just did one as a draft, not sure if you can see it? https://github.com/publiclab/PublicLab.Editor/releases/edit/untagged-a61a5484f15db4097723

Also, we can resolve this pinned issue pretty soon! https://github.com/publiclab/PublicLab.Editor/issues/721 and https://github.com/publiclab/PublicLab.Editor/issues/743 !! 🎉

**Comment by NARUDESIGNS** [comment]
> So, all the changes since then (Apr 13, 2021) can be included into v3.1.0 - what do you say?

Hello, @jywarren sorry for the late response here. Where can I find all the changes since April 13th, 2021?
Forgive me I've not participated in an upgrade like this before so I'm a little lost as to what changes we'd be making, esp to the PublicLab Editor

**Comment by jywarren** [comment]
So if you can see this link, when you create a new release it will compile a list automatically from the commit log: https://github.com/publiclab/PublicLab.Editor/releases/edit/untagged-a61a5484f15db4097723

If you try it yourself (i'm not sure you can see it but we'll discuss today) it'd be here: https://github.com/publiclab/PublicLab.Editor/releases/new

**Comment by jywarren** [comment]
Look out for Popper library addition for error handling in HTML template: https://github.com/publiclab/PublicLab.Editor/pull/771/files

**Comment by NARUDESIGNS** [comment]
Hello, I've updated the version number here - [publiclab/PublicLab.Editor#833](https://github.com/publiclab/PublicLab.Editor/pull/833)

**Comment by jywarren** [comment]
Excellent. Let's re-run the "release notes" auto-generation and publish the release!

**Comment by jywarren** [comment]
Let me know how `npm publish` goes! Doesn't have to be tonight :-)

**Comment by NARUDESIGNS** [comment]
Hi @jywarren where are we on this progress, please?
I checked the **publish branch to npm...* task since we have that out of the way.

**Comment by jywarren** [comment]
Great, i checked "open a matching PR on plots2 for this new version # (or let Dependabot do it)" - https://github.com/publiclab/plots2/pull/10711

**Comment by vedant-z** [comment]
Hey @jywarren I want to complete this issue " publish to live github-pages demo (so people can see the latest version running in the demo) (from within GitPod works well)" as it seems like this will complete the whole issue. I need some help on this
